version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - coolify
    # Add this section for port mapping
    ports:
      - "3000:3000" # Host_port:Container_port
    expose:
      - "3000" # Internal port your app runs on
    environment:
      DATABASE_URI: "${DATABASE_URI}"
      PAYLOAD_SECRET: "${PAYLOAD_SECRET}"
      NEXT_PUBLIC_SERVER_URL: "${NEXT_PUBLIC_SERVER_URL}"
      GCS_CREDENTIALS: "${GCS_CREDENTIALS}"
      GCS_BUCKET: "${GCS_BUCKET}"
      GCS_PROJECT_ID: "${GCS_PROJECT_ID}"
      GCS_CREDENTIALS_ENCRYPT: "${GCS_CREDENTIALS_ENCRYPT}"

networks:
  coolify:
    external: true